name: Multiple / Matrix (Tag & Commit)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule:
          [ports/nvim, ports/mdBook, ports/vscode-icons, ports/aur-packages]
        include:
          - submodule: ports/nvim
            strategy: "tag"
            latest: "latestTag"
          - submodule: ports/mdBook
            strategy: "commit"
            latest: "latestShortCommitSha"
          - submodule: ports/vscode-icons
            strategy: "commit"
            latest: "latestShortCommitSha"
          - submodule: ports/aur-packages
            strategy: "tag"
            latest: "latestTag"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Update Submodules
        id: submodules
        uses: sgoudham/update-git-submodules@caec228ba25f49179eac6263b6fd0d19bd258537
        with:
          submodules: ${{ matrix.submodule }}
          strategy: ${{ matrix.strategy }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.submodules.outputs[format('{0}--updated', matrix.submodule)] }}
        with:
          commit-message: "feat: update ${{ matrix.submodule }} to ${{ steps.submodules.outputs[format('{0}--{1}', matrix.submodule, matrix.latest)] }}"
          branch: "feat/update-${{ matrix.submodule }}-${{ steps.submodules.outputs[format('{0}--{1}', matrix.submodule, matrix.latest)] }}"
          title: "feat: update ${{ matrix.submodule }} submodule to ${{ steps.submodules.outputs[format('{0}--{1}', matrix.submodule, matrix.latest)] }}"
          body: ${{ steps.submodules.outputs.prBody }}
