name: Multiple / Single PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  single:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "multiple-submodule"
          submodules: "recursive"
          fetch-depth: 0

      - name: Update Submodules
        id: submodules
        uses: "sgoudham/update-git-submodules@main"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: update all submodules"
          branch: "feat/update-all-submodules"
          title: "feat: update all submodules"
          body: ${{ steps.submodules.outputs.updatedMarkdownTable }}
