name: Single / Single PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  single:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "single-submodule"
          submodules: "recursive"
          fetch-depth: 0

      - name: Update Submodules
        id: submodules
        uses: "sgoudham/update-git-submodules@main"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.submodules.outputs['ports/vscode-icons--latestTag'] }}
        with:
          commit-message: "feat: update catppuccin/vscode-icons to ${{ steps.submodules.outputs['ports/vscode-icons--latestTag'] }}"
          branch: "feat/update-vscode-icons-${{ steps.submodules.outputs['ports/vscode-icons--latestTag'] }}"
          title: "feat: update catppuccin/vscode-icons submodule to ${{ steps.submodules.outputs['ports/vscode-icons--latestTag'] }}"
          body: ${{ steps.submodules.outputs.prBody }}.
